### ISSUE TITLE
Fonts to include

### ISSUE THREAD

**Issue by raphaelbastide** [raphaelbastide/usemodify#1]
List moved, made private.

**Comment by LucasLeBihan** [comment]
http://gutenberg.osdn.jp/en/license.html EN - JPN font catalog

**Comment by sebastiangraz** [comment]
http://dogesans.info/ – CC 4.0

**Comment by jjjlllnnn** [comment]
Archivo Narrow : https://www.behance.net/gallery/26368789/Archivo-Narrow
Alegreya https://github.com/huertatipografica/Alegreya-libre
Alegreya Sans https://github.com/huertatipografica/Alegreya-Sans

**Comment by raphaelbastide** [comment]
https://www.are.na/laurel-schwulst/open-source-web-fonts
